import type { Command } from "../Command.ts";
import type { Context } from "../Context.ts";
import { DridockError } from "../../domain/errors.ts";
import { allVerbNames } from "../../domain/Verbs.ts";

/**
 * `dridock completion bash` — emit a bash completion script. Ports
 * cb_completion_bash at wrapper.sh:1025. install.sh drops the output
 * into `~/.local/share/bash-completion/completions/<binname>`.
 */
export class CompletionCommand implements Command {
  readonly verb = "completion" as const;

  async run(args: readonly string[], ctx: Context): Promise<number> {
    const shell = args[0];
    if (shell === undefined || shell === "") {
      ctx.stderr.write(`usage: ${ctx.binName} completion bash\n`);
      return 1;
    }
    if (shell !== "bash") {
      throw new DridockError(`completion: unsupported shell '${shell}' (bash only for now)`);
    }
    const prog = ctx.binName;
    const topVerbs = allVerbNames().join(" ");
    // Static bash completion script — matches wrapper.sh:1027 shape.
    ctx.stdout.write(`# ${prog} bash completion — generated by \`${prog} completion bash\`.
# Install: ${prog} completion bash > ~/.local/share/bash-completion/completions/${prog}
_${prog}_complete() {
    local cur cword
    cur="\${COMP_WORDS[COMP_CWORD]}"
    cword=\$COMP_CWORD

    local top_verbs="${topVerbs}"

    if [ "\$cword" -eq 1 ]; then
        COMPREPLY=( \$(compgen -W "\$top_verbs" -- "\$cur") )
        return 0
    fi

    case "\${COMP_WORDS[1]}" in
        vm)               COMPREPLY=( \$(compgen -W "ls list usage df gc" -- "\$cur") ) ;;
        features|profiles) COMPREPLY=( \$(compgen -W "list enable disable info" -- "\$cur") ) ;;
        consult)          COMPREPLY=( \$(compgen -W "list show approve revise reject post watch" -- "\$cur") ) ;;
        framework-bugs)   COMPREPLY=( \$(compgen -W "list clear" -- "\$cur") ) ;;
        checkversion)     COMPREPLY=( \$(compgen -W "--all" -- "\$cur") ) ;;
        destroy)          COMPREPLY=( \$(compgen -W "--purge" -- "\$cur") ) ;;
        migrate)          COMPREPLY=( \$(compgen -W "--all" -- "\$cur") ) ;;
        browser-bridge)   COMPREPLY=( \$(compgen -W "up down" -- "\$cur") ) ;;
        host-agent)       COMPREPLY=( \$(compgen -W "up down status" -- "\$cur") ) ;;
        harness)          COMPREPLY=( \$(compgen -W "sync" -- "\$cur") ) ;;
        completion)       COMPREPLY=( \$(compgen -W "bash" -- "\$cur") ) ;;
        start)            COMPREPLY=( \$(compgen -W "-p --output-format --model --system-prompt --append-system-prompt --json-schema --effort --resume --no-continue --update" -- "\$cur") ) ;;
    esac
}
complete -F _${prog}_complete ${prog}
`);
    return 0;
  }
}
