import type { FileSystem } from "../infra/FileSystem.ts";
import type { HostCommandRunner } from "../infra/HostCommandRunner.ts";
import type { MachineConfig } from "./MachineConfig.ts";
import { cbNum } from "../domain/units.ts";

/**
 * `dridock bootstrap` — the scaffolding service. Ports the essential shape
 * of cb_bootstrap at wrapper.sh:1877 (which itself composes cb_write_brief,
 * cb_init_project_config, cb_write_readme, cb_write_sample).
 *
 * Not a Command yet — the BootstrapCommand wraps this. Kept as a service
 * so the flag-parsing logic in the command stays small.
 */
export interface BootstrapOptions {
  readonly root: string;
  readonly flavor: "greenfield" | "adopt" | "workspace";
  readonly mode: "full" | "brief-only";
  readonly force: boolean;
  readonly intent: string;
}

export interface BootstrapDeps {
  readonly fs: FileSystem;
  readonly host: HostCommandRunner;
  readonly machine: MachineConfig;
  readonly onNotice: (message: string) => void;
}

export type BootstrapOutcome =
  | { readonly kind: "brief-exists" }
  | { readonly kind: "done"; readonly flavor: BootstrapOptions["flavor"]; readonly id: string };

/** Ports cb_gen_id — 8 lowercase-hex chars. */
export function generateProjectId(rand: (n: number) => number = Math.random): string {
  const hex = "0123456789abcdef";
  let s = "";
  for (let i = 0; i < 8; i++) s += hex[Math.floor(rand(16) * 16)];
  return s;
}

export class BootstrapService {
  constructor(private readonly deps: BootstrapDeps, private readonly idGen: () => string = generateProjectId) {}

  async run(opts: BootstrapOptions): Promise<BootstrapOutcome> {
    const briefPath = `${opts.root}/.dridock/BRIEF.md`;
    if ((await this.deps.fs.exists(briefPath)) && !opts.force) {
      return { kind: "brief-exists" };
    }
    const dotDir = `${opts.root}/.dridock`;
    await this.deps.fs.mkdirRecursive(dotDir);

    if (opts.mode === "full") {
      switch (opts.flavor) {
        case "adopt": /* skip greenfield scaffolding — existing repo */ break;
        case "workspace":
          if (!(await this.deps.fs.isDirectory(`${opts.root}/.git`))) {
            // `git init` — we intentionally don't shell out here; the
            // caller supplies the runner in BootstrapCommand for the
            // wider cloning paths.
            await this.deps.host.runCapture(`git -C ${shellEscape(opts.root)} init -q`);
            this.deps.onNotice(`  ✓ git init (orchestration parent)\n`);
          }
          await this.writeReadmeIfMissing(opts.root);
          break;
        default:
          await this.deps.host.runCapture(`git -C ${shellEscape(opts.root)} init -q`);
          this.deps.onNotice(`  ✓ git init\n`);
          await this.writeReadmeIfMissing(opts.root);
          await this.deps.fs.mkdirRecursive(`${opts.root}/workloads`);
          await this.deps.fs.writeText(`${opts.root}/workloads/.gitkeep`, "");
          break;
      }
    }

    // BRIEF.md — always written
    await this.writeBrief(briefPath, opts);
    this.deps.onNotice(`  ✓ .dridock/BRIEF.md\n`);

    // config.yml — always written (via a small template)
    const id = await this.writeInitialConfig(opts.root);
    this.deps.onNotice(`  ✓ .dridock/config.yml (gitignored)\n`);

    // gitignore always ensured
    await this.ensureGitignore(opts.root);

    return { kind: "done", flavor: opts.flavor, id };
  }

  /**
   * cb_init_project_config equivalent — writes `.dridock/config.yml` with
   * a generated id + baked sizing (or machine-config defaults if set).
   * Returns the project id it wrote.
   */
  private async writeInitialConfig(root: string): Promise<string> {
    const configPath = `${root}/.dridock/config.yml`;
    const id = this.idGen();
    const cpu = cbNumOr(await this.deps.machine.machineDefault("vm.default_cpu"), 4);
    const memory = await this.deps.machine.machineDefault("vm.default_memory") ?? "8GiB";
    const disk = await this.deps.machine.machineDefault("vm.default_disk") ?? "60GiB";
    const content = `# .dridock/config.yml — generated by the wrapper; edit to taste. Gitignored.
id: ${id}
vm:
  cpu: ${cpu}
  memory: ${memory}
  disk: ${disk}
  autostop: false         # stop the VM when the harness container exits
network:
  hostname:               # optional: set e.g. "myproj" for a friendly http://myproj:<port> — 'dridock net' also sets this
# features: []            # opt-in tool bundles, e.g. [typescript, python] — list them: 'dridock features'
`;
    await this.deps.fs.writeTextAtomic(configPath, content, { mode: 0o644 });
    return id;
  }

  /**
   * Ensure `.gitignore` contains the machine-local dot-dir lines. Ports
   * cb_ensure_gitignore at wrapper.sh:422 — safe to run repeatedly.
   */
  private async ensureGitignore(root: string): Promise<void> {
    if (!(await this.deps.fs.isDirectory(`${root}/.git`))) return;   // matches bash guard
    const gitignorePath = `${root}/.gitignore`;
    const existing = (await this.deps.fs.readTextOrUndefined(gitignorePath)) ?? "";
    const wanted = [
      "/.dridock/config.yml",
      "/.dridock/secrets.env",
      "/.claudebox/config.yml",
      "/.claudebox/secrets.env",
    ];
    let next = existing;
    for (const line of wanted) {
      if (!next.split("\n").includes(line)) {
        next = (next.length > 0 && !next.endsWith("\n") ? next + "\n" : next) + line + "\n";
      }
    }
    if (next !== existing) await this.deps.fs.writeTextAtomic(gitignorePath, next);
  }

  private async writeReadmeIfMissing(root: string): Promise<void> {
    const path = `${root}/README.md`;
    if (await this.deps.fs.exists(path)) return;
    const name = root.split("/").pop() ?? "project";
    await this.deps.fs.writeText(path, `# ${name}\n\nBootstrapped by dridock. See \`.dridock/BRIEF.md\` for the mission brief.\n`);
    this.deps.onNotice(`  ✓ README.md\n`);
  }

  private async writeBrief(briefPath: string, opts: BootstrapOptions): Promise<void> {
    const flavorLine = {
      "adopt": "**Flavor:** adopt (existing repo)",
      "workspace": "**Flavor:** multi-repo orchestration parent",
      "greenfield": "**Flavor:** greenfield",
    }[opts.flavor];
    const intent = opts.intent.trim() === "" ? "_(no intent provided — edit this file to describe what you're building)_" : opts.intent.trim();
    const content = `# Mission brief

${flavorLine}

## Intent

${intent}

## Progress / handoff log

- _(add entries as the project evolves)_
`;
    await this.deps.fs.writeTextAtomic(briefPath, content, { mode: 0o644 });
  }
}

/** Escape a path for safe use inside a shell single-quoted argument.
 *  Simple: wrap in single quotes and escape any embedded single quotes. */
function shellEscape(s: string): string {
  return `'${s.replaceAll("'", "'\\''")}'`;
}

function cbNumOr(s: string | undefined, fallback: number): number {
  if (s === undefined) return fallback;
  try { return Math.floor(cbNum(s)); } catch { return fallback; }
}
